USE [InfinityDev]
GO

/****** Object:  UserDefinedTableType [dbo].[Infinity_LPLB_Type]    Script Date: 4/21/2020 1:11:28 PM ******/
DROP TYPE [dbo].[Infinity_LPLB_Type]
GO

/****** Object:  UserDefinedTableType [dbo].[Infinity_LPLB_Type]    Script Date: 4/21/2020 1:11:28 PM ******/
CREATE TYPE [dbo].[Infinity_LPLB_Type] AS TABLE(
	[IDInfinity] [bigint] IDENTITY(1,1) NOT NULL,
	[Defendant_Company] [varchar](255) NULL,
	[Status_of_Case_Ex_ADST] [varchar](255) NULL,
	[Year_Filed] [smallint] NULL,
	[First_Files_Date] [date] NULL,
	[Termination_Date] [date] NULL,
	[Lead_Case_Venue] [varchar](255) NULL,
	[Type_of_Case_10b_11_14e_14a] [varchar](255) NULL,
	[Lead_Case_No_Example_1100409] [varchar](255) NULL,
	[First_Jurisdiction_Filed_and_Number] [varchar](255) NULL,
	[KTMC_Marketing_PlanDesignation] [varchar](255) NULL,
	[Second_Jurisdiction_Filed_and_Number] [varchar](255) NULL,
	[Third_Jurisdiction_Filed_and_Number] [varchar](255) NULL,
	[Fourth_Jurisdiction_Filed_and_Number] [varchar](255) NULL,
	[First_Press_Release_Date] [date] NULL,
	[Lead_Plaintiff_Deadline] [varchar](255) NULL,
	[Lead_Plaintiff_Movant1_Type_InsitutionalIndividualMixed] [varchar](255) NULL,
	[LP_Appointment_Date] [date] NULL,
	[Appointed_Lead_Plaintiff] [varchar](511) NULL,
	[Appointed_Lead_Plaintiff_Type_EX_Individual_Institution_Group_of] [varchar](255) NULL,
	[Largest_Loss_Appointed_YesNo] [varchar](255) NULL,
	[Judge_that_Appointed_LP] [varchar](255) NULL,
	[Judge_Assigned_to_Lead_Case] [varchar](255) NULL,
	[Magistrate_Judge] [varchar](255) NULL,
	[Lead_Counsel_1_] [varchar](255) NULL,
	[Lead_Counsel_2] [varchar](255) NULL,
	[Lead_Counsel_3] [varchar](255) NULL,
	[Lead_Counsel_4] [varchar](255) NULL,
	[Appointed_Local_Liaison_Counsel] [varchar](255) NULL,
	[Appointed_Additional_Counsel] [varchar](255) NULL,
	[Corporate_Defense_Counsel_1_] [varchar](255) NULL,
	[Attorney_for_Corporate_Defense_Counsel_1] [varchar](255) NULL,
	[Corporate_Defense_Counsel_2] [varchar](255) NULL,
	[Attorney_for_Corporate_Defense_Counsel_2] [varchar](255) NULL,
	[Corporate_Defense_Counsel_3] [varchar](255) NULL,
	[Attorney_for_Corporate_Defense_Counsel_3] [varchar](255) NULL,
	[Corporate_Defense_Counsel_4] [varchar](255) NULL,
	[KTMC_Internal_Case_No] [varchar](255) NULL,
	[Initial_Damage_Estimate_from_60day_list] [varchar](255) NULL,
	[LP__of_Estimated_Class_Loss_LPs_loss_from_landscape_divided_by_t] [varchar](255) NULL,
	[Date_of_Order_on_1st_MTD] [date] NULL,
	[The_1st_MTD_Result] [varchar](255) NULL,
	[The_1st_MTD_Judge] [varchar](255) NULL,
	[Date_of_Order_on_2nd_MTD] [date] NULL,
	[The_2nd_MTD_Result] [varchar](255) NULL,
	[The_2nd_MTD_Judge] [varchar](255) NULL,
	[Date_of_Order_on_3rd_MTD] [date] NULL,
	[The_3rd_MTD_Result] [varchar](255) NULL,
	[The_3rd_MTD_Judge] [varchar](255) NULL,
	[Date_of_Class_Cert_Decision] [date] NULL,
	[Class_Cert_Result] [varchar](255) NULL,
	[Class_Cert_Judge] [varchar](255) NULL,
	[Certified_Class_Period] [varchar](1023) NULL,
	[Is_Certified_Class_Period_Same_as_Original_Class_Period_YN] [varchar](255) NULL,
	[Stipulation_of_Settlement_Filed_Date] [date] NULL,
	[Settlement_Type_cash_stock_mixed] [varchar](255) NULL,
	[Settlement_Stage_Examples_Motion_to_dismiss_summary_judgment_cla] [varchar](255) NULL,
	[Settlement_Hearing_Date] [date] NULL,
	[Settling_Lead_Plaintiffs] [varchar](511) NULL,
	[Final_Settlement_Date] [date] NULL,
	[Settlement_Amount] [varchar](255) NULL,
	[Settlement_Attorneys_Fees_] [varchar](511) NULL,
	[Requested_Attorneys__Fee_Percentage] [varchar](255) NULL,
	[Attorneys_Fee_Percentage_Awarded_] [varchar](255) NULL,
	[Fee_Lodestar] [varchar](255) NULL,
	[Settling_Parties_Company_Individual_Auditor_Underwriter] [varchar](255) NULL,
	[Settlement_Judge] [varchar](255) NULL,
	[Mediator] [varchar](255) NULL,
	[Defendant_Insurer] [varchar](255) NULL,
	[Certified_Class_Representative1] [varchar](255) NULL,
	[Certified_Class_Representative2] [varchar](255) NULL,
	[Certified_Class_Representative3] [varchar](255) NULL,
	[Certified_Class_Representative4] [varchar](255) NULL,
	[Certified_Class_Representative5] [varchar](255) NULL,
	[Date_KTMC_paid] [date] NULL,
	[Defendant_Underwriter] [varchar](255) NULL
)
GO


